baseURL: "https://gatomalo.dev/"
languageCode: "en-us"
title: "Gato Malo"
theme: "PaperMod-Nord"
enableEmoji: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
disqusShortname: gato-malo

menu:
  main:
  - identifier: about
    name: About
    url: /about/
  - identifier: blog
    name: Blog
    url: "/blog/"

params:

  defaultTheme: dark
  comments: true

  keywords:
    - nitzan zada
    - game
    - games
    - game dev
    - throne of mithril
    - blade point
    - game blog
    - throne
    - mithril

  label:
    icon: /img/logo.png

  profileMode:
    enabled: true
    title: "Gato Malo"
    subtitle: "An indie game developer with [**an insane cat**](/about/#the-cat)"
    imageUrl: "/img/logo.png"
    imageWidth: 256
    imageHeight: 256

    buttons:
      - name: Blog
        url: "/blog/"
      # - name: Blade Point
      #   url: "/tags/bladepoint/"
      - name: Throne of Mithril
        url: "/tags/throne/"

  socialIcons:
    - name: "github"
      url: "https://github.com/mastern2k3"
    - name: "dev"
      url: "https://dev.to/mastern2k3"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nitzanzada/"
